print("mi segundo programa")
print("Ingrese su nombre")
sNombre= input()
print("Ingrese su edad")
sEdad= input()
print("Ingrese su carrera")
sCarrera= input()
print("Ingrese su Carne")
sCarne= input()
print("Nombre: " + sNombre)
print("Edad: " + sEdad)
print("Carrera: " + sCarrera)
print("Carne: " + sCarne)

print("soy " + sNombre + ", tengo " + sEdad + " años y estudio la carrera " + sCarrera + " mi numero de carne es " + sCarne)